fixed qt5 build..again

diff --git a/LxQt5-current/Deps/qt5/qt5.SlackBuild b/LxQt5-current/Deps/qt5/qt5.SlackBuild
--- a/LxQt5-current/Deps/qt5/qt5.SlackBuild
+++ b/LxQt5-current/Deps/qt5/qt5.SlackBuild
@@ -1,122 +1,152 @@
 #!/bin/sh
-
-# Slackware build script for qt5
-
-# Copyright 2015 Thorn Inurcide 
-# Copyright 2013-2014 Larry Hajali <larryhaja[at]gmail[dot]com>
-# Copyright 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013  Patrick J. Volkerding, Sebeka, MN, USA
+# Generated by Alien's SlackBuild Toolkit: http://slackware.com/~alien/AST
+# Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015  Eric Hameleers, Eindhoven, Netherlands
+# Copyright 2015  Thorn Inurcide USA
 # All rights reserved.
 #
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
+#   Permission to use, copy, modify, and distribute this software for
+#   any purpose with or without fee is hereby granted, provided that
+#   the above copyright notice and this permission notice appear in all
+#   copies.
 #
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
-#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
-#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-
-# Merged some ideas from Alex Sarmardzic's script for qt4 at SlackBuilds.org
-# ^^ Modified by Robby Workman <rworkman@slackware.com> for QT4 & KDE4
-
-# We're using qt-copy instead of a released qt version, as this git release
-# has at least one bugfix strongly recommended by the kde developers.
-
-# Obtained from:
-# git clone git://gitorious.org/+kde-developers/qt/kde-qt.git
-# git checkout origin/4.5.3-patched
-# git checkout origin/4.6.0-stable-patched
-# git checkout origin/4.6.1-patched
-# git checkout origin/4.7.0-patched
-#
-# Alternate method (we don't use this):
-# wget http://qt.gitorious.org/qt/kde-qt/archive-tarball/4.6.2-patched
-#
-# Modifications 2010, 2011, 2012  Eric Hameleers, Eindhoven, NL
-# qt 4.7.3, 4.7.4, 4.8.0, 4.8.1, 4.8.2, 4.8.4 are built from original nokia sources.
-
-# This is the highly modified version qt.SlackBuild found in Slackware
-# tailored to Qt 5. Modified by Larry Hajali.
-
-# Modified for my LxQt SlackBuilds. Version 0.8.0, 0.9.0
-# Not using Git Version as above
-
-# With help from Ryan P.C. McQuen Copyright 2015
-# Thanks! 
+#   THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
+#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
+#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
+#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
+#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
+#   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
+#   SUCH DAMAGE.
+#   
+#   Based off the build at SBo and with help from Ryan P.C. McQuen:
 
 PRGNAM=qt5
 VERSION=${VERSION:-5.4.1}
 SHORTVER=`echo $VERSION | cut -d. -f1-2`
 BUILD=${BUILD:-1}
+NUMJOBS=${NUMJOBS:-" -j4 "}
 TAG=${TAG:-_thorn}
 
-wget -c http://anychimirror101.mirrors.tds.net/pub/Qt/archive/qt/${SHORTVER}/${VERSION}/single/qt-everywhere-opensource-src-${VERSION}.tar.xz
+DOCS="README"
 
-if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
-  esac
-fi
+SRCDIR=$(cd $(dirname $0); pwd)
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp/thorn}
+TMP=${TMP:-/tmp/build}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "armv7hl" ]; then
-  # To prevent "qatomic_armv6.h error: output number 2 not directly addressable"
-  # More permanent solution is to patch gcc:
-  # http://bazaar.launchpad.net/~linaro-toolchain-dev/gcc-linaro/4.6/revision/106731
-  SLKCFLAGS="-O2 -march=armv7-a -mfpu=vfpv3-d16 -fno-strict-volatile-bitfields"
-  LIBDIRSUFFIX=""
+SOURCE="$SRCDIR/${PRGNAM}-${VERSION}.tar.xz"
+SRCURL="http://download.qt.io/archive/qt/${SHORTVER}/${VERSION}/single/qt-everywhere-opensource-src-${VERSION}.tar.xz"
+
+# You can use your own private machine.conf file to overrule machine defaults:
+if [ -e $SRCDIR/machine.conf ]; then
+  . $SRCDIR/machine.conf
+elif [ -e /etc/slackbuild/machine.conf ]; then
+  . /etc/slackbuild/machine.conf
 else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
+  # Automatically determine the architecture we're building on:
+  MARCH=$( uname -m )
+  if [ -z "$ARCH" ]; then
+    case "$MARCH" in
+      i?86)    export ARCH=i486 ;;
+      armv7hl) export ARCH=$MARCH ;;
+      armv6hl) export ARCH=$MARCH ;;
+      arm*)    export ARCH=arm ;;
+      # Unless $ARCH is already set, use uname -m for all other archs:
+      *)       export ARCH=$MARCH ;;
+    esac
+  fi
+  # Set CFLAGS/CXXFLAGS and LIBDIRSUFFIX:
+  case "$ARCH" in
+    i486)      SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+               SLKLDFLAGS=""; LIBDIRSUFFIX=""
+               ;;
+    x86_64)    SLKCFLAGS="-O2 -fPIC"
+               SLKLDFLAGS="-L/usr/lib64"; LIBDIRSUFFIX="64"
+               ;;
+    armv7hl)   SLKCFLAGS="-O2 -march=armv7-a -mfpu=vfpv3-d16 -fno-strict-volatile-bitfields"
+               SLKLDFLAGS=""; LIBDIRSUFFIX=""
+               ;;
+    armv6hl)   SLKCFLAGS="-O2 -march=armv6 -mfpu=vfp -mfloat-abi=hard"
+               SLKLDFLAGS=""; LIBDIRSUFFIX=""
+               ;;
+    *)         SLKCFLAGS=${SLKCFLAGS:-"O2"}
+               SLKLDFLAGS=${SLKLDFLAGS:-""}; LIBDIRSUFFIX=${LIBDIRSUFFIX:-""}
+               ;;
+  esac
 fi
 
-set -e
+case "$ARCH" in
+    arm*)    TARGET=$ARCH-slackware-linux-gnueabi ;;
+    *)       TARGET=$ARCH-slackware-linux ;;
+esac
 
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $TMP
-rm -rf ${PRGNAM/5/}-everywhere-opensource-src-$VERSION
-tar xvf $CWD/${PRGNAM/5/}-everywhere-opensource-src-$VERSION.tar.xz
-cd ${PRGNAM/5/}-everywhere-opensource-src-$VERSION
+set -e
+trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PRGNAM}.log' ERR
+set -u
+P1=${1:-1}
+
+# Save old umask and set to 0022:
+_UMASK_=$(umask)
+umask 0022
+
+# Create working directories:
+mkdir -p $OUTPUT        
+mkdir -p $TMP/tmp-$PRGNAM 
+mkdir -p $PKG             
+rm -rf $PKG/*            
+rm -rf $TMP/tmp-$PRGNAM/* 
+rm -rf $OUTPUT/{checkout,configure,make,install,error,makepkg,patch}-$PRGNAM.log
+
+# Source file availability:
+if ! [ -f ${SOURCE} ]; then
+  echo "Source '$(basename ${SOURCE})' not available yet..."
+  # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
+  [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
+  if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
+  if ! [ "x${SRCURL}" == "x" ]; then
+    echo "Will download file to $(dirname $SOURCE)"
+    wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
+    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+      echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+      mv -f "${SOURCE}" "${SOURCE}".FAIL
+      exit 1
+    fi
+  else
+    echo "File '$(basename ${SOURCE})' not available... aborting the build."
+    exit 1
+  fi
+fi
+
+if [ "$P1" == "--download" ]; then
+  echo "Download complete."
+  exit 0
+fi
+
+cd $TMP/tmp-$PRGNAM
+echo "Extracting the source archive(s) for $PRGNAM..."
+if $(file ${SOURCE} | grep -qi ": 7-zip"); then
+  7za x ${SOURCE}
+elif $(file ${SOURCE} | grep -qi ": zip"); then
+  unzip ${SOURCE}
+else
+  tar -xvf ${SOURCE}
+fi
+cd qt-everywhere-opensource-src-${VERSION}
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+chmod -R u+w,go+r-w,a+rX-st .
 
 # Slackware patch to build against MySQL/MariaDB.
-patch -p1 < $CWD/patches/qt5.mysql.h.diff
+patch -p1 < $SRCDIR/patches/qt5.mysql.h.diff
 
 # Install path fix for libplatformplugin.so.
-# https://bugs.webkit.org/show_bug.cgi?id=117077
-patch -p1 < $CWD/patches/platformplugin-install-path-fix.patch
+patch -p1 < $SRCDIR/patches/platformplugin-install-path-fix.patch
 
 # Limit -reduce-relocations to ix86 and x86_64.
-# https://bugreports.qt-project.org/browse/QTBUG-36129
 if echo $ARCH | grep -q '\(i.86\|x86_64\)' 2>/dev/null; then
   RELOCATIONS="-reduce-relocations"
 else
@@ -129,7 +159,6 @@ fi
 
 # Not using Pulseaudio 
 sed -i '/qtwebengine/d' qt.pro
-
 
 export CFLAGS="$SLKCFLAGS"
 export CXXFLAGS="$SLKCFLAGS"
@@ -162,14 +191,31 @@ export OPENSOURCE_CXXFLAGS="$SLKCFLAGS"
   -no-rpath \
   -no-strip \
   -release \
-  $RELOCATIONS \
   -no-pulseaudio \
   -nomake examples \
+  $RELOCATIONS \
 
-make -j3
+make $NUMJOBS || exit 1
 make install INSTALL_ROOT=$PKG
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+# Add this to the doinst.sh:
+mkdir -p $PKG/install
+cat <<EOINS >> $PKG/install/doinst.sh
+# Update the desktop database:
+if [ -x usr/bin/update-desktop-database ]; then
+  chroot . /usr/bin/update-desktop-database usr/share/applications > /dev/null 2>&1
+fi
+
+# Update hicolor theme cache:
+if [ -d usr/share/icons/hicolor ]; then
+  if [ -x /usr/bin/gtk-update-icon-cache ]; then
+    chroot . /usr/bin/gtk-update-icon-cache -f -t usr/share/icons/hicolor 1> /dev/null 2> /dev/null
+  fi
+fi
+
+EOINS
+
+find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 ln -s $PRGNAM $PKG/usr/lib${LIBDIRSUFFIX}/qt-$VERSION
@@ -189,9 +235,9 @@ done
 
 # Create Environment variables
 mkdir -p $PKG/etc/profile.d
-sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $CWD/profile.d/$PRGNAM.sh \
+sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $SRCDIR/profile.d/$PRGNAM.sh \
   > $PKG/etc/profile.d/$PRGNAM.sh
-sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $CWD/profile.d/$PRGNAM.csh \
+sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $SRCDIR/profile.d/$PRGNAM.csh \
   > $PKG/etc/profile.d/$PRGNAM.csh
 chmod 0755 $PKG/etc/profile.d/*
 
@@ -237,34 +283,38 @@ done
 # One more for the road.
 sed -i "s|$PWD/qtbase|/usr/lib${LIBDIRSUFFIX}/$PRGNAM|" \
   $PKG/usr/lib${LIBDIRSUFFIX}/$PRGNAM/mkspecs/modules/qt_lib_bootstrap_private.pri
-
-for i in $CWD/desktop/*.desktop; do
+  
+# Add desktop files:  
+for i in $SRCDIR/desktop/*.desktop; do
   install -D -m 0644 $i $PKG/usr/share/applications/$(basename $i)
 done
 sed -i "s|@LIBDIR@|$LIBDIRSUFFIX|" $PKG/usr/share/applications/*
 
-install -D -m 0644 qttools/src/assistant/assistant/images/assistant-128.png \
-  $PKG/usr/share/icons/hicolor/128x128/apps/assistant.png
-install -D -m 0644 qttools/src/designer/src/designer/images/designer.png \
-  $PKG/usr/share/icons/hicolor/128x128/apps/designer.png
-install -D -m 0644 qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
-  $PKG/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png
-for i in 16 32 48 64 128; do
-  install -D -m 0644 qttools/src/linguist/linguist/images/icons/linguist-${i}-32.png \
-    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/linguist.png
-done
+# Add the icons:
+mkdir -p $PKG/usr/share/icons/hicolor/{16x16/apps,32x32/apps,48x48/apps,64x64/apps,128x128/apps}
+install -m 0644 $SRCDIR/icons/16x16/*.png $PKG/usr/share/icons/hicolor/16x16/apps/
+install -m 0644 $SRCDIR/icons/32x32/*.png $PKG/usr/share/icons/hicolor/32x32/apps/
+install -m 0644 $SRCDIR/icons/48x48/*.png $PKG/usr/share/icons/hicolor/48x48/apps/
+install -m 0644 $SRCDIR/icons/64x64/*.png $PKG/usr/share/icons/hicolor/64x64/apps/
+install -m 0644 $SRCDIR/icons/128x128/*.png $PKG/usr/share/icons/hicolor/128x128/apps/
+
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION || true
+cat $SRCDIR/$(basename $0) > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
+find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
 find $PKG \( -name "*.qml" -o -name "*.app" \) -perm 755 -exec chmod 644 '{}' \;
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  README qtbase/{header*,LGPL_EXCEPTION.txt,LICENSE.*L} \
-  $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-
 mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
+cat $SRCDIR/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
+makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+cd $OUTPUT
+md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz}.md5
+cd -
+cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt
+
+# Restore the original umask:
+umask ${_UMASK_}
